"""add_profile_picture_to_user

Revision ID: d4bc58e30b66
Revises: 90450323f409
Create Date: 2025-05-23 10:53:33.317505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4bc58e30b66'
down_revision = '90450323f409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_analyses_id', table_name='market_analyses')
    op.drop_table('market_analyses')
    op.drop_index('ix_stock_analyses_id', table_name='stock_analyses')
    op.drop_table('stock_analyses')
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.create_table('stock_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prediction_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='stock_analyses_stock_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_analyses_pkey')
    )
    op.create_index('ix_stock_analyses_id', 'stock_analyses', ['id'], unique=False)
    op.create_table('market_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('market_trend', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('volatility_index', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sector_performance', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_sentiment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='market_analyses_pkey')
    )
    op.create_index('ix_market_analyses_id', 'market_analyses', ['id'], unique=False)
    # ### end Alembic commands ###
